### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by BaiLiping** [Lin-Sinorodin/Military_Vehicles_Tracking#1]
hey Lin, nice work! where did you get the dataset?

**Comment by Lin-Sinorodin** [comment]
Thanks! 
I scraped it from Google.
During the time I worked on this project, there wasn't any dataset available so I had to do it myself.

You can find the dataset files [here](https://drive.google.com/file/d/1I6P-eGWoqM0-2oKSzTHnIIS5fuDvskHD/view) in the `dataset` directory.
Also, check out this [notebook](https://github.com/Lin-Sinorodin/Military_Vehicles_Tracking/blob/main/src/utils/Google_images.ipynb) and maybe some of the scripts [here](https://github.com/Lin-Sinorodin/Military_Vehicles_Tracking/tree/main/src/utils) if you are interested in expanding the dataset yourself.
