### ISSUE TITLE
How to process a long video?

### ISSUE THREAD

**Issue by oldoc** [Lin-Sinorodin/Military_Vehicles_Tracking#3]
When I try to track a long video, I got the error blew:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[39], line 23
     20 tracker = MultiObjectTracker(video, results_path, detector)
     22 # iterate over the frames in the video
---> 23 for frame, bounding_boxes in tracker:
     24     plot_bounding_boxes(frame, bounding_boxes)
     25     tracker.video_writer.write(frame)

File ~/code/Military_Vehicles_Tracking/Military_Vehicles_Tracking/src/tracker.py:21, in MultiObjectTracker.__iter__(self)
     18 tracking = None
     20 for frame in tqdm(self.video, desc='Tracking', unit='frame', total=self.video.num_frames):
---> 21     bbox_xywh, bbox_conf, bbox_classes = self._detect_image_for_deepsort(frame)
     23     if bbox_conf is not None and len(bbox_conf):
     24         tracking = self.deepsort.update(bbox_xywh, bbox_conf, bbox_classes, frame)

File ~/code/Military_Vehicles_Tracking/Military_Vehicles_Tracking/src/tracker.py:34, in MultiObjectTracker._detect_image_for_deepsort(self, image)
     30 """
     31 Convert detections from YOLOv5 output to the needed format in DeepSORT.
     32 """
     33 bbox_df = self.detector(image).pandas().xywh[0]
---> 34 bbox_xywh = torch.Tensor(bbox_df[['xcenter', 'ycenter', 'width', 'height']].to_numpy())
     35 bbox_conf = torch.Tensor(bbox_df[['confidence']].to_numpy())
     36 bbox_classes = torch.Tensor(bbox_df[['class']].to_numpy())

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

Thanks!

**Comment by oldoc** [comment]
It report the error listed above if there is no target in the 1st frame.

**Comment by ahmetybilgin** [comment]
How did you solve this mate?
